from decimal import Decimal

H2S_PPM_TO_MG_M3 = Decimal("1.40")
H2S_RFC_MG_M3 = Decimal("0.002")

HOURS_PER_DAY = Decimal("24")
DAYS_PER_YEAR = Decimal("365")

ARKL_CALCULATION_VERSION = "1.1.0-MVP"

RQ_WITHIN_REFERENCE_LEVEL = "WITHIN_REFERENCE_LEVEL"
RQ_ABOVE_REFERENCE_LEVEL = "ABOVE_REFERENCE_LEVEL"
